INSERT INTO ticker_types (code, description, asset_class, locale)
VALUES ('CS','Common Stock','stocks','us'),
       ('PFD','Preferred Stock','stocks','us'),
       ('WARRANT','Warrant','stocks','us'),
       ('RIGHT','Rights','stocks','us'),
       ('BOND','Corporate Bond','stocks','us'),
       ('ETF','Exchange Traded Fund','stocks','us'),
       ('ETN','Exchange Traded Note','stocks','us'),
       ('ETV','Exchange Traded Vehicle','stocks','us'),
       ('SP','Structured Product','stocks','us'),
       ('ADRC','American Depository Receipt Common','stocks','us'),
       ('ADRP','American Depository Receipt Preferred','stocks','us'),
       ('ADRW','American Depository Receipt Warrants','stocks','us'),
       ('ADRR','American Depository Receipt Rights','stocks','us'),
       ('FUND','Fund','stocks','us'),
       ('BASKET','Basket','stocks','us'),
       ('UNIT','Unit','stocks','us'),
       ('LT','Liquidating Trust','stocks','us'),
       ('OS','Ordinary Shares','stocks','us'),
       ('GDR','Global Depository Receipts','stocks','us'),
       ('OTHER','Other Security Type','stocks','us'),
       ('NYRS','New York Registry Shares','stocks','us'),
       ('AGEN','Agency Bond','stocks','us'),
       ('EQLK','Equity Linked Bond','stocks','us'),
       ('ETS','Single-security ETF','stocks','us'),
       ('IX','Index','indices','us'),
       ('CRYPTO','Crypto Currency','crypto','global'),
       ('FX','Forex (Foreign Exchange)','fx','global');
